taxi_trip:
  outputs:
    dev:
      dataset: taxi_trip
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: <path/to/your-credentials.json>
      location: US
      method: service-account
      priority: interactive
      project: <your-projects>
      threads: 1
      type: bigquery
  target: dev
