version: 2
sources:
    - name: staging
      database: "iykra-370008"
      schema: yellow_taxi
      tables:
        - name: yellow_tripdata_2019-01
        - name: yellow_tripdata_2019-02
        - name: yellow_tripdata_2019-03
        - name: yellow_tripdata_2019-04
        - name: yellow_tripdata_2019-05
        - name: yellow_tripdata_2019-06
        - name: yellow_tripdata_2019-07
        - name: yellow_tripdata_2019-08
        - name: yellow_tripdata_2019-09
        - name: yellow_tripdata_2019-10
        - name: yellow_tripdata_2019-11
        - name: yellow_tripdata_2019-12
